### ISSUE TITLE
Which is a license of TriOrm, GPL or Apache License 2.0?

### ISSUE THREAD

**Issue by keima** [HendrixString/Android-TriOrm#1]
see: https://github.com/HendrixString/Android-TriOrm/blob/master/LICENSE
and https://github.com/HendrixString/Android-TriOrm/blob/master/README.md#terms

Conflicting license LICENSE file and README.md.
Which is correct?

**Comment by HendrixString** [comment]
Hello

Apache 2.

Hope it helps

**Comment by keima** [comment]
Thanks!
